# Generated by Django 3.1.6 on 2021-05-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Walk', models.CharField(default='none', max_length=10)),
                ('invent', models.CharField(default='none', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appoint', models.CharField(default='none', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Services', models.CharField(default='none', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue', models.CharField(max_length=20, null=True)),
                ('select', models.CharField(choices=[('None', 'None'), ('Vehicle1', 'Interior Tire Repair'), ('vehicle2', 'Radiator Overhaul'), ('vehicle3', 'Welding'), ('vehicle4', 'Jack Repair'), ('vehicle5', 'Tire Repair'), ('vehicle6', 'Interior')], max_length=50, null=True)),
                ('Appointme', models.ManyToManyField(to='vibalist.Customer')),
                ('home', models.ManyToManyField(to='vibalist.Home')),
                ('papa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vibalist.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Seconddisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('Vehicle', models.CharField(choices=[('tr', '6 Wheels Up'), ('ca', '4 Wheels'), ('ja', '3 Wheels'), ('mo', '2 Wheels')], default='none', max_length=10)),
                ('seconds', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vibalist.admin')),
            ],
        ),
        migrations.CreateModel(
            name='InputLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Log', models.CharField(max_length=20, null=True)),
                ('Pass', models.CharField(max_length=20, null=True)),
                ('second', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vibalist.admin')),
            ],
        ),
        migrations.CreateModel(
            name='FourthPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itr', models.CharField(max_length=20, null=True)),
                ('ro', models.CharField(max_length=20, null=True)),
                ('wg', models.CharField(max_length=20, null=True)),
                ('jr', models.CharField(max_length=20, null=True)),
                ('it', models.CharField(max_length=20, null=True)),
                ('Quants1', models.CharField(max_length=20, null=True)),
                ('Quants2', models.CharField(max_length=20, null=True)),
                ('Quants3', models.CharField(max_length=20, null=True)),
                ('Quants4', models.CharField(max_length=20, null=True)),
                ('Quants5', models.CharField(max_length=20, null=True)),
                ('Quants6', models.CharField(max_length=20, null=True)),
                ('ttl', models.IntegerField(null=True)),
                ('Appointme1', models.ManyToManyField(to='vibalist.Customer')),
                ('home1', models.ManyToManyField(to='vibalist.Home')),
                ('pap1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vibalist.admin')),
            ],
        ),
        migrations.CreateModel(
            name='fifthAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client', models.CharField(max_length=20, null=True)),
                ('Contact', models.CharField(max_length=20, null=True)),
                ('dateofsched', models.DateTimeField(null=True)),
                ('timeofsched', models.DateTimeField(null=True)),
                ('pangbyahe', models.CharField(choices=[('six', '6 Wheels Up'), ('four', 'four Wheels'), ('three', '3 Wheels'), ('two', '2 Wheels')], default='none', max_length=10)),
                ('fifth', models.ManyToManyField(to='vibalist.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='AnimHomeservices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('CP', models.CharField(max_length=20, null=True)),
                ('Add', models.CharField(max_length=20, null=True)),
                ('arawngpunta', models.DateTimeField(null=True)),
                ('Orasngpunta', models.DateTimeField(null=True)),
                ('sasakyan', models.CharField(choices=[('hay', '6 Wheels Up'), ('hey', 'four Wheels'), ('hiy', '3 Wheels'), ('hoy', '2 Wheels')], default='none', max_length=10)),
                ('anim', models.ManyToManyField(to='vibalist.Home')),
            ],
        ),
    ]
