# Generated by Django 3.1.6 on 2021-06-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibalist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduling',
            name='sltss',
        ),
        migrations.AddField(
            model_name='scheduling',
            name='selecthome',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='selecthouse',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='selectonline',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
