# Generated by Django 3.1.6 on 2021-04-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibalist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='choice',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='coursesection',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
