# Generated by Django 3.1.6 on 2021-04-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibalist', '0002_auto_20210423_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Gmail',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='letter',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
