# Generated by Django 3.1.6 on 2021-06-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibalist', '0002_auto_20210623_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduling',
            name='selecthome',
        ),
        migrations.RemoveField(
            model_name='scheduling',
            name='selecthouse',
        ),
        migrations.RemoveField(
            model_name='scheduling',
            name='selectonline',
        ),
        migrations.AddField(
            model_name='scheduling',
            name='select',
            field=models.CharField(choices=[('selecthome', 'Home Visiting'), ('selectonline', 'Online'), ('selecthouse', 'Teacher House')], default='none', max_length=25),
        ),
    ]
