# Generated by Django 3.1.6 on 2021-04-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibalist', '0003_auto_20210424_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('lalaki', 'MALE'), ('babae', 'FEMALE')], default='none', max_length=10),
        ),
    ]
