# Generated by Django 3.1.6 on 2021-06-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibalist', '0004_auto_20210623_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='TOTAL2',
            field=models.IntegerField(null=True),
        ),
    ]
