# Generated by Django 3.1.6 on 2021-04-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibalist', '0004_item_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gender',
        ),
        migrations.AddField(
            model_name='item',
            name='lesson',
            field=models.CharField(choices=[('lec', 'LESSON'), ('lab', 'LABARATORY'), ('all', 'BOTH')], default='none', max_length=10),
        ),
    ]
