# Generated by Django 3.1.6 on 2021-06-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibalist', '0006_auto_20210623_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='place',
            field=models.CharField(choices=[('1', 'Mindanao'), ('2', 'Visayas'), ('3', 'Luzon'), ('4', 'Metro Manila')], default='none', max_length=25),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='select',
            field=models.CharField(choices=[('1', 'Home Visiting'), ('2', 'Online'), ('3', 'Teacher House')], default='none', max_length=25),
        ),
    ]
