# Generated by Django 3.1.6 on 2021-06-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibalist', '0008_auto_20210623_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='grad',
            field=models.CharField(choices=[('1', 'BANK ACCOUNT'), ('2', 'GCASH'), ('3', 'CREDIT CARD')], default='none', max_length=25),
        ),
    ]
