# Generated by Django 3.1.6 on 2021-06-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibalist', '0009_auto_20210623_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='grad',
            field=models.CharField(choices=[('1', 'Undergraduate'), ('2', 'Graduate Degree')], default='none', max_length=25),
        ),
    ]
