# Generated by Django 3.1.6 on 2021-06-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibalist', '0011_auto_20210623_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='select',
            field=models.CharField(choices=[('Home Visiting', 'Home Visiting'), ('Online', 'Online'), ('Teacher House', 'Teacher House')], default='none', max_length=25),
        ),
    ]
