# Generated by Django 3.1.6 on 2021-06-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibalist', '0012_auto_20210624_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='place',
            field=models.CharField(choices=[('Mindanao', 'Mindanao'), ('Visayas', 'Visayas'), ('Luzon', 'Luzon'), ('Metro Manila', 'Metro Manila')], default='none', max_length=25),
        ),
    ]
