# Generated by Django 3.1.6 on 2021-06-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibalist', '0013_auto_20210624_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='selectsss',
            field=models.CharField(choices=[('BANK ACCOUNT', 'BANK ACCOUNT'), ('GCASH', 'GCASH'), ('CREDIT CARD', 'CREDIT CARD')], default='none', max_length=25),
        ),
    ]
