# Generated by Django 3.1.6 on 2021-06-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibalist', '0014_auto_20210624_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='place',
            field=models.CharField(choices=[('1', 'Mindanao'), ('2', 'Visayas'), ('3', 'Luzon'), ('4', 'Metro Manila')], default='none', max_length=25),
        ),
    ]
