# Generated by Django 3.1.6 on 2021-06-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibalist', '0019_auto_20210625_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='grad',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate Degree', 'Graduate Degree')], default='none', max_length=25),
        ),
    ]
